import React from 'react';
import { motion } from 'motion/react';
import { Image as ImageIcon, Video, FileText, Globe, ArrowRight, Zap, Shield, Sparkles } from 'lucide-react';

interface LandingPageProps {
  onGetStarted: (module?: string) => void;
  t: (key: string) => string;
}

export function LandingPage({ onGetStarted, t }: LandingPageProps) {
  const modules = [
    { id: 'artwork', title: 'ARTWORK STUDIO', desc: 'Cover art, thumbnails & socials — generated by AI in seconds.', icon: ImageIcon, color: 'from-cyan-400 to-teal-500', accent: 'text-turquoise' },
    { id: 'video', title: 'VIDEO ENGINE', desc: 'Cinematic loops & teasers for Reels, TikTok and Stories.', icon: Video, color: 'from-purple-500 to-violet-600', accent: 'text-purple-neon' },
    { id: 'epk', title: 'PRESS KIT', desc: 'Professional bio, press releases & EPK — ready for labels.', icon: FileText, color: 'from-pink-500 to-rose-600', accent: 'text-pink-400' },
    { id: 'smart-link', title: 'SMART LINK', desc: 'One link for all platforms — Spotify, Apple, YouTube & more.', icon: Globe, color: 'from-emerald-400 to-green-500', accent: 'text-emerald-400' },
  ];

  const features = [
    { icon: Zap, title: 'Instant Generation', desc: 'No design skills needed. Describe your vision, AI delivers.' },
    { icon: Shield, title: 'Your Art, Your Rights', desc: 'Full ownership of everything you create. No hidden fees.' },
    { icon: Sparkles, title: 'Multi-Language', desc: 'Create content in English, French, Spanish, Italian & German.' },
  ];

  return (
    <div className="min-h-screen flex flex-col overflow-hidden bg-[#050505] relative">
      {/* Background orbs */}
      <div className="absolute top-[-20%] left-[-15%] w-[60%] h-[60%] neon-glow-turquoise rounded-full pointer-events-none" />
      <div className="absolute bottom-[-20%] right-[-15%] w-[60%] h-[60%] neon-glow-purple rounded-full pointer-events-none" />

      {/* Hero */}
      <section className="relative z-10 flex-1 flex flex-col items-center justify-center px-6 pt-24 pb-16 lg:pt-32">
        <motion.div
          initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
          className="text-center max-w-4xl mx-auto space-y-6"
        >
          {/* Logo */}
          <motion.img
            src="/logo-musaic.jpeg"
            alt="Musaic AI"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6 }}
            className="w-24 h-24 lg:w-32 lg:h-32 rounded-3xl mx-auto shadow-2xl shadow-cyan-500/30 animate-glow-ring"
          />

          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/5 border border-white/10 text-xs font-semibold text-white/60 tracking-wider uppercase">
            <Sparkles className="w-3.5 h-3.5 text-turquoise" />
            AI-Powered Visual Suite for Musicians
          </div>

          <h1 className="text-5xl sm:text-6xl lg:text-8xl font-black uppercase tracking-tight leading-[0.9]">
            <span className="text-white">Your Music.</span><br />
            <span className="shimmer-text">Your Brand.</span>
          </h1>

          <p className="text-lg lg:text-xl text-white/50 font-medium max-w-2xl mx-auto leading-relaxed">
            The all-in-one AI platform for independent artists. Generate cover art, videos, press kits and smart links — all from a single studio.
          </p>

          <motion.button
            onClick={() => onGetStarted()}
            whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
            className="inline-flex items-center gap-3 px-10 py-5 bg-turquoise text-black font-black uppercase tracking-widest text-sm rounded-2xl shadow-[0_0_40px_rgba(0,255,221,0.3)] hover:shadow-[0_0_60px_rgba(0,255,221,0.4)] transition-shadow"
          >
            Start Creating — It's Free
            <ArrowRight className="w-5 h-5" />
          </motion.button>

          <p className="text-white/30 text-xs font-medium">50 free tokens on signup. No credit card required.</p>
        </motion.div>
      </section>

      {/* Module Grid */}
      <section className="relative z-10 px-6 pb-20">
        <div className="max-w-5xl mx-auto grid grid-cols-1 sm:grid-cols-2 gap-4 lg:gap-6">
          {modules.map((mod, idx) => (
            <motion.button
              key={mod.id}
              initial={{ opacity: 0, y: 40 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + idx * 0.1, duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
              onClick={() => onGetStarted(mod.id)}
              className="group relative glass-card glass-card-hover rounded-3xl p-8 text-left overflow-hidden"
            >
              <div className={`absolute top-0 right-0 w-40 h-40 bg-gradient-to-bl ${mod.color} opacity-5 group-hover:opacity-10 rounded-full blur-3xl transition-opacity duration-500 -mr-10 -mt-10`} />

              <div className="relative z-10 flex flex-col gap-5">
                <div className={`w-14 h-14 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center ${mod.accent} group-hover:scale-110 transition-transform duration-500`}>
                  <mod.icon className="w-7 h-7" />
                </div>
                <div>
                  <h3 className="text-xl font-black uppercase tracking-tight text-white group-hover:text-turquoise transition-colors">
                    {mod.title}
                  </h3>
                  <p className="text-sm text-white/40 font-medium mt-2 leading-relaxed">{mod.desc}</p>
                </div>
                <div className="flex items-center gap-2 text-white/20 group-hover:text-turquoise transition-colors">
                  <span className="text-xs font-bold uppercase tracking-widest">Explore</span>
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </div>
              </div>
            </motion.button>
          ))}
        </div>
      </section>

      {/* Features Strip */}
      <section className="relative z-10 border-t border-white/5 bg-[#050505]">
        <div className="max-w-5xl mx-auto px-6 py-16 grid grid-cols-1 md:grid-cols-3 gap-10">
          {features.map((feat, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.8 + idx * 0.15 }}
              className="flex flex-col items-center text-center gap-4"
            >
              <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-turquoise">
                <feat.icon className="w-6 h-6" />
              </div>
              <h4 className="text-sm font-black uppercase tracking-wider text-white">{feat.title}</h4>
              <p className="text-xs text-white/40 leading-relaxed max-w-xs">{feat.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>
    </div>
  );
}
